version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8000:8000
    volumes:
    - ./:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    links:
      - redis:redis

  redis:
    restart: always
    image: redis:6.0-rc4-alpine
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A djelegram worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
  
